# Site settings
title:       "Блог Сергея"
header_title: "Блог Сергея"
email:       seventyseventh@gmail.com
author:      Сергей Грабак
description: "Блог Сергея"
baseurl:     ""
url:         "https://tolive.github.io"
date_format: "%-d.%m.%Y"

# Google services
google_analytics: ""
google_verification: ""

# Facebook
facebook_app_id: ""

# Optional features
animated:             true
show_related_posts:   false
show_post_footer:    false
show_social_icons:    true
ajaxify_contact_form: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: "tolive-1"

# Social icons
github_username: tolive
bitbucket_username:
stackoverflow_id:
twitter_username: SergeiGrabak
google_plus_id:
linkedin_username:
facebook_username: 
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
instagram_username:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    "/:title/"
paginate:     15
sass:
  compressed: true

# Gems
gems: [jekyll-paginate]
